# Generated by Django 4.2.16 on 2024-11-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Youth Exchange', 'Youth Exchange'), ('Training Course', 'Training Course'), ('Conference', 'Conference'), ('Transnational Meeting', 'Transnational Meeting')], default='Youth Exchange', max_length=50),
            preserve_default=False,
        ),
    ]
