# Generated by Django 5.1.5 on 2025-02-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_project_location_project_city_project_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('submitted_by', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
